add pipline design pattern project
devblogs-ir/PipelineDesignPattern pull request #1
Opened 2023-12-18 18:07 UTC by mojtabavali

2023-12-18 18:53 UTC, mohammadKarimi commented
there are some mistakes which you can fix them as soon as passible before merging:

1- The ExceptionHandling method catches all exceptions and prints a generic "catched" message with the exception message.
2- You can use  specific exception types such as CountryBlockedException instead throw new Exception.
3- You can use const pattern matching instead of == operator.
4- I prefer to add required keyword to IP property. because i want to show the framework this property is required on construction phase.
5- finally, Delegate Naming. for practice is good. but in real application you must use Action instead of creating a new delegate type.

2023-12-18 18:55 UTC, mohammadKarimi requested changes
Please follow my comments.

2023-12-21 07:25 UTC, mojtabavali commented
thanks for your comment. I changed codes base on your comment.

2023-12-21 11:42 UTC, mohammadKarimi approved these changes
Perfect.

2023-12-21 11:42 UTC, mohammadKarimi commented on src/MojtabaValizadeh/PipelineDesignPattern/CountryBlockedException.cs
> +    public CountryBlockedExceptionHandler(string message) : base(message) { }
Perfect 👍

2023-12-21 11:42 UTC, mohammadKarimi commented on src/MojtabaValizadeh/PipelineDesignPattern/Framework.cs
> +        if(httpContent.Ip is "192.168.0.130")
perfect.

2023-12-21 11:42 UTC, mohammadKarimi commented on src/MojtabaValizadeh/PipelineDesignPattern/Framework.cs
> +        if(httpContent.Ip is "192.168.0.130")
however you consider that you should check the nullability of httpContext before.

2023-12-21 11:42 UTC, mohammadKarimi commented on src/MojtabaValizadeh/PipelineDesignPattern/Framework.cs
> +        catch (CountryBlockedExceptionHandler e)
perfect.

2023-12-21 11:43 UTC, merged