davood baghdadi
devblogs-ir/PipelineDesignPattern pull request #11
Opened 2023-12-19 21:39 UTC by davobag

Davood Baghdadi 

      In this Application:
      -The console app asks about geo locatopn with 2 two   alternatives : iran and usa this part is an equivalent of IP checking.
      -Then the app asks about of user id. It can be equivalent of user role. which userId=1 has access to every thing.
      -Finally app asks about what are you looking for? It is also works as Routing. It means to which controller are you going to go.
```

2023-12-20 07:08 UTC, mohammadKarimi requested changes

2023-12-20 07:08 UTC, mohammadKarimi commented on src/Davood Baghdadi/PipelineDesignPattern/Framework.cs
> +            Thread.Sleep(2000);
it's important to avoid blocking threads in a real application

2023-12-20 07:08 UTC, mohammadKarimi commented on src/Davood Baghdadi/PipelineDesignPattern/Framework.cs
> +                    throw new Exception("Service to your location is not possible now!");
You are throwing a general Exception with a message in the ExceptionHandling method. It's generally a good practice to use more specific exception types or create custom exception classes for different types of errors

2023-12-20 07:08 UTC, mohammadKarimi commented on src/Davood Baghdadi/PipelineDesignPattern/Framework.cs
> +                if (http.IP == "iran")
Consider avoiding magic strings like "iran".
please use constant matching instead == operator.

2023-12-20 07:08 UTC, mohammadKarimi commented on src/Davood Baghdadi/PipelineDesignPattern/Framework.cs
> +        public void AuthenticationHandling(HTTPContext http, Action<HTTPContext> authAction)
consider using more concise and descriptive names, such as HandleException, HandleAuthentication

2023-12-20 07:08 UTC, mohammadKarimi commented on src/Davood Baghdadi/PipelineDesignPattern/Framework.cs
> +            catch (Exception ex)
this line catches all exceptions.

2023-12-26 20:26 UTC, davobag commented on src/Davood Baghdadi/PipelineDesignPattern/Pipes/EndPointPipe.cs
this endpoint class compare incomming controller and action with all available  controllers and actions of web application.(IN CONTROLLER FOLDER)

2023-12-26 20:26 UTC, davobag commented on src/Davood Baghdadi/PipelineDesignPattern/NotFoundUrlException.cs
when any controller or action has not been this exception fires.It is some how similar to 404 error. not found page.

2023-12-26 20:26 UTC, davobag commented on src/Davood Baghdadi/PipelineDesignPattern/GeoLocationException.cs
this exception is related to  forbiden ip addresses which in this application simulated by an input handy!

2023-12-28 17:05 UTC, closed without merging