PipelineDesignPattern Project
devblogs-ir/PipelineDesignPattern pull request #22
Opened 2023-12-20 17:53 UTC by aminafra

2023-12-21 11:40 UTC, mohammadKarimi requested changes

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +			throw new Exception(message: "Iranian IPs are blocked");
Throwing a generic Exception is not recommended. It's better to create a custom exception type that provides more information about the error.

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +		if (httpContext.Country is CountryIPPAddress.Iran)
There is no null check for the httpContext parameter in both methods.

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +		if (httpContext.Country is CountryIPPAddress.Iran)
if (httpContext is null)
        {
                throw new ArgumentNullException(nameof(httpContext));
        }

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +			throw new Exception(message: "Iranian IPs are blocked");
public class IranianIPBlockedException : Exception
{
    public IranianIPBlockedException(string message) : base(message)
    {
    }
}

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/HttpContext.cs
> +public enum CountryIPPAddress
Naming convention, 
IPP ??

2023-12-21 11:40 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/HttpContext.cs
> +    public required string IP { get; set; }
required 👍

2023-12-21 17:39 UTC, aminafra commented
I tried to fix these issues

2023-12-23 06:29 UTC, mohammadKarimi approved these changes
I will merge your code. but consider you shouldn't catch all Exceptions, in this scenario.

2023-12-23 06:29 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +        ArgumentNullException.ThrowIfNull(httpContext);
Perfect.

2023-12-23 06:29 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +        if (httpContext.Country is CountryIPAddress.Iran)
constant pattern matching 👍

2023-12-23 06:29 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +            throw new IranianIPBlockedException(message: "Iranian IPs are blocked");
Custom Exception 👍

2023-12-23 06:29 UTC, mohammadKarimi commented on src/Amin Afrasiabi/PipelineDesignPattern/Framework.cs
> +        catch (Exception ex)
this block catches all type of Exception. it is better approach to catch issue related.

2023-12-23 06:29 UTC, merged