Feat/sara gholampour
devblogs-ir/PipelineDesignPattern pull request #23
Opened 2023-12-22 09:01 UTC by saragholampour971

2023-12-23 06:45 UTC, mohammadKarimi requested changes

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/DuplicateStageException.cs
> +    public DuplicateStageException() : base("you pass this Stage !")
Custom Exception 👍

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/Program.cs
> +ExceptionHandler framework = new();
where do you use framework object?

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +    public delegate void OO();
Naming convention
what is the meaning of OO?

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +    public void handleOmletCycle(OO cycle)
naming conventions public method naming must follow Pascal naming.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            catch (Exception e)
you are catching all exceptions.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +        var ans= Console.ReadLine();
Naming Convention:
what is the meaning of ans? 
is it answer?

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +   public delegate string OAction();
Again Naming Conventions, OAction. what is O.
you should Use Action instead of defining your own delegate.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletContext.cs
> +    public static List<string> cookLine = new List<string>{};
Naming Convention, 
Please Use Collection Expression. 
like public static List<string> CookLine = [];


and moreover, aware of static property.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletContext.cs
> +    public static List<string> cookLine = new List<string>{};
if you are using static property, it is better to make it immutable, Like IReadOnlyList<T>

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +        catch (Exception e)
You are catching all exceptions. it is not good.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletContext.cs
> +    public static List<string> instructions = new List<string>
Naming Convention.
and moreover, aware of static property.

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            validateStage(func);
Why you want to call validateStage again?

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            saveStage(func);
Why you are calling saveStage again?

2023-12-23 06:45 UTC, mohammadKarimi commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            OmletContext.cookLine.Add(result);
What happens if in validate stage, your code have an exception?

2023-12-23 09:44 UTC, saragholampour971 commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            validateStage(func);
to if input value not valid ,trying to get new value

2023-12-23 09:55 UTC, saragholampour971 commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +            OmletContext.cookLine.Add(result);
that is why i called validate stage in catch , if input value not valid , trying to get new value from user.

2023-12-23 10:50 UTC, saragholampour971 commented on src/SaraGholampour/OmletPipeline/OmletController.cs
> +        catch (Exception e)
could you please give me some hint or references about how to do that.

2023-12-24 10:24 UTC, mohammadKarimi approved these changes
Perfect.

2023-12-24 10:25 UTC, merged