Feat/niloufar mont
devblogs-ir/PipelineDesignPattern pull request #27
Opened 2023-12-26 13:12 UTC by lilmont

Pipeline tool:
> maha-builder --ip "someIp" --url "someUrl"

"localhost:xxxx/Products/GetUserById/3"
"localhost:xxxx/Products/GetAllProducts"

2023-12-28 20:52 UTC, thisisnabi requested changes

2023-12-28 20:52 UTC, thisisnabi commented on src/Niloo Mont/PipelineCLITool/Framework.cs
> +            else
You can remove this `else`

2023-12-28 20:52 UTC, thisisnabi commented on src/Niloo Mont/PipelineCLITool/Framework.cs
> +                    var convertToType = $"To{parameterList[i].ParameterType.Name}";
Please move this logic in a helper class named model Binder for binding method parameters

2023-12-28 20:52 UTC, thisisnabi commented on src/Niloo Mont/PipelineCLITool/Program.cs
> +for (int i = 0; i < args.Length; i++)
Move this code into the another method!
Don't write Spaghetti code

2023-12-29 13:49 UTC, lilmont commented on src/Niloo Mont/PipelineCLITool/Framework.cs
> +                    var convertToType = $"To{parameterList[i].ParameterType.Name}";
Done.

2023-12-29 13:49 UTC, lilmont commented on src/Niloo Mont/PipelineCLITool/Program.cs
> +for (int i = 0; i < args.Length; i++)
Sure, thank you for the great feedback.

2023-12-29 15:47 UTC, thisisnabi approved these changes

2023-12-29 15:47 UTC, merged