Feat/abolfazl kabiri
devblogs-ir/PipelineDesignPattern pull request #4
Opened 2023-12-18 22:42 UTC by KabiriAbolfazl

2023-12-19 05:25 UTC, thisisnabi commented
That was so hard to understand, Keep it simple, stupid, please follow our example.
And I will present your implementation in next coder session.

2023-12-19 05:29 UTC, KabiriAbolfazl commented
> That was so hard to understand, Keep it simple, stupid, please follow our example. And I will present your implementation in next coder session.

I agree with you.

2023-12-19 05:45 UTC, KabiriAbolfazl commented
> > That was so hard to understand, Keep it simple, stupid, please follow our example. And I will present your implementation in next coder session.
> 
> I agree with you.

I'll push a new implementation

2023-12-19 07:05 UTC, mohammadKarimi requested changes
totally your coding style is perfect, but you have to aware of needless complexity. 
Please Keep it Simple.

2023-12-19 07:05 UTC, mohammadKarimi commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/IranianAuthenticationStep.cs
- File Scoped namespace
- invert IF
- Naming Convention ( EndPoint vs EndPoind??)
- Remove line space
-

2023-12-19 07:49 UTC, KabiriAbolfazl commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/IranianAuthenticationStep.cs
Thanks for great review and your hints dear Mohammad

2023-12-20 08:09 UTC, mohammadKarimi requested changes

2023-12-20 08:09 UTC, mohammadKarimi commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/AmericanAuthenticationStep.cs
> +    private bool ValidateIpAddress(IPipelineContext context)
In both IranianAuthenticationStep and AmericanAuthenticationStep, the ValidateIpAddress method throws an InvalidCastException if the IP address cannot be parsed. Consider using a more specific exception type

2023-12-20 08:09 UTC, mohammadKarimi commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/AmericanAuthenticationStep.cs
> +    {
The IranianAuthenticationStep and AmericanAuthenticationStep classes share similar code.
DRY 🥇

2023-12-20 08:09 UTC, mohammadKarimi commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Framework/IranianAuthenticationStep.cs
> +            if (!context.RequestIpAddress.Split('.')[0].Equals("194")) // sample for american ip range
magic string. for practice it is ok, consider don't use like this in real application.

2023-12-20 08:09 UTC, mohammadKarimi commented on src/Abolfazl Kabiri/PipelineDesignPattern.SimpleImplement/Pipeline/Pipeline.cs
> +    public void ExecutePipeline()
for single line of method, 
you can use => instead { }

2023-12-20 17:53 UTC, mohammadKarimi approved these changes
Perfect.

2023-12-20 17:54 UTC, merged