adding sample pipeline
devblogs-ir/PipelineDesignPattern pull request #6
Opened 2023-12-19 17:07 UTC by Javidleo

## Summary
adding sample request pipe line with delegates.

## Changes
- adding Exception Handler
- adding Authorization Handler
- adding CORS Handler
- Prevent Ip's Starting with 192.168 (Iran IP example) to Use Service.

2023-12-20 06:48 UTC, mohammadKarimi requested changes

2023-12-20 06:48 UTC, mohammadKarimi commented on src/Javid Hassani/PipelineDesignPattern/PipelineDesignPattern/Context.cs
for 1 or 2 property, it is better to use primary constructor.
Record :) like.

2023-12-20 06:48 UTC, mohammadKarimi commented on src/Javid Hassani/PipelineDesignPattern/PipelineDesignPattern/Exceptions/ForbiddenAccessException.cs
> +public class ForbiddenAccessException(string message) : Exception(message)
Custom Exception 👍

2023-12-20 06:48 UTC, mohammadKarimi commented on src/Javid Hassani/PipelineDesignPattern/PipelineDesignPattern/Pipe.cs
> +        catch (Exception ex)
this line catches all type of Exception 👎 
you should develop issue related exception

2023-12-20 06:48 UTC, mohammadKarimi commented on src/Javid Hassani/PipelineDesignPattern/PipelineDesignPattern/Program.cs
> +var pipe = new Pipe();
Target Type Expression is better. ( I Like it) but you can not to use it.

2023-12-20 06:48 UTC, mohammadKarimi commented on src/Javid Hassani/PipelineDesignPattern/PipelineDesignPattern/UserService.cs
> +        if (user == null)
it is better to use constant matching instead == operator

2023-12-20 07:37 UTC, Javidleo commented
Thanks for review. I will make changes then notify you to review it again.

2023-12-20 10:50 UTC, Javidleo commented
@mohammadKarimi  @thisisnabi  
new changes as you requested.

2023-12-21 11:47 UTC, mohammadKarimi approved these changes
Perfect

2023-12-21 11:47 UTC, merged