function chaining practice done
devblogs-ir/PipelineDesignPattern pull request #7
Opened 2023-12-19 18:20 UTC by smjebelli

Exception handling if the IP is from Islamic Republic!! using chained functions.

2023-12-20 06:54 UTC, mohammadKarimi requested changes

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +    public class Framewrok()
useless default constructor.
remove it

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +        catch (Exception ex)
this lice captures all type of exception, please develop issue related exceptions

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +        if (context.IP.Contains("Iran"))
IP format is XXX.XXX.XXX.XXX, it does not contain of Iran.

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +            throw new Exception("Sorry you are accessing from Islamic Republic.");
Throw Issue Related Exception

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +
while space, try to write code in pretty format.

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/HttpContext.cs
> +    public class HttpContext
you can use, record, 
or add required keyword to property.

2023-12-20 06:54 UTC, mohammadKarimi commented on src/MohammadJebelli/PipelineDesignPattern/Program.cs
> +        framework.Authentication(context, controller.GetAllUser)
Pretty format for improving readability.

2023-12-20 12:11 UTC, smjebelli commented on src/MohammadJebelli/PipelineDesignPattern/Framewrok.cs
> +        if (context.IP.Contains("Iran"))
the reason I used this approach was to simplify.
Should I use a package like IPInfo to extract IP location?

2023-12-20 12:32 UTC, smjebelli commented
Thanks for your review.
Suggested changes applied

2023-12-21 11:49 UTC, mohammadKarimi approved these changes
Perfect

2023-12-21 11:49 UTC, merged