Feat/mahdi salahinia
devblogs-ir/PipelineDesignPattern pull request #9
Opened 2023-12-19 21:12 UTC by mahdisalahi

Exercise of the fourth session

2023-12-20 07:02 UTC, mohammadKarimi requested changes

2023-12-20 07:02 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CountryIp.cs
> +            {
please use Expression collection in .net 8

2023-12-20 07:02 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +        public void ExceptionHandling(Action action, string ip)
you should pass context which contains IP Address in Action and parameter.

2023-12-20 07:02 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +        public void ExceptionHandling(Action action, string ip)
there is no try and catch block to capture exceptions.

2023-12-21 07:30 UTC, mahdisalahi reviewed
Refactor

2023-12-21 11:54 UTC, mohammadKarimi requested changes

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CountryIp.cs
> +        public List<string> IranIps { get; set; } = ["192.168.22.7", "192.168.22.8", "192.168.22.9"];
consider you are exposing List<T>, and this type is mutable object. it means who wants to add or remove an item from this list, he/she can do. 
so, you must return IReadOnlyList instead of List.

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CountryIp.cs
> +namespace PipelineDesignPatternExp
use file scoped namespace.

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +            var ips = new CountryIp();
The variable name 'ips' is not very descriptive. Consider using a more meaningful name that reflects its purpose, such as countryIpList

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +            if (ips.IranIps.Contains(httpContext.IpAddress))
There is no null check for the 'httpContext' parameter

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +                "Access Denied".Dump();
there is no throwing an exception.

2023-12-21 11:54 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +            catch (Exception e)
catching a generic Exception is not recommended. It's better to create a custom exception type that provides more information about the error.

2023-12-23 07:29 UTC, mohammadKarimi requested changes

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +        else
If you are using throw, so there is no need to write else block.

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CustomException.cs
> +namespace PipelineDesignPatternExp
File Scoped Namespace.

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CustomException.cs
> +using System.Linq;
Remove Unused using. or Use Ctrl+K+E in Visual Studio

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +            throw new CustomException("Authentication was unsuccessful");
this method is ExceptionHandling, Why you are trying to throw exception again? 
you should catch exceptions

try{}
catch(CustomException ex)

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/HttpContext.cs
> +namespace PipelineDesignPatternExp
again namespace.

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/HttpContext.cs
> +        public string IpAddress { get; set; }
you can use required keyword in this scenraio.

2023-12-23 07:29 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/Framework.cs
> +using static System.Collections.Specialized.BitVector32;
What is it?

2023-12-24 10:28 UTC, mohammadKarimi approved these changes
Perfect.

2023-12-24 10:28 UTC, mohammadKarimi commented on src/Mahdi Salahinia/PipelineDesignPatternExp/CountryIp.cs
> +    public IReadOnlyList<string> IranIps { get; set; } = ["192.168.22.7", "192.168.22.8", "192.168.22.9"];
Perfect.

2023-12-24 10:28 UTC, merged